#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("nfc_app.Resource", IsApplication=true)]

namespace nfc_app
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int cardArray = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int usersArray = 2131099649;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_menu_preferences = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001b
			public const int adFbButton = 2131296283;
			
			// aapt resource value: 0x7f09000a
			public const int addCardButton = 2131296266;
			
			// aapt resource value: 0x7f09001c
			public const int addFriendButton = 2131296284;
			
			// aapt resource value: 0x7f09001e
			public const int askMoneyButton = 2131296286;
			
			// aapt resource value: 0x7f090005
			public const int btnCreateAccount = 2131296261;
			
			// aapt resource value: 0x7f090013
			public const int btnDialogProceed = 2131296275;
			
			// aapt resource value: 0x7f090019
			public const int btnMakePayment = 2131296281;
			
			// aapt resource value: 0x7f090007
			public const int carTypeSpinner = 2131296263;
			
			// aapt resource value: 0x7f090009
			public const int cardNrInput = 2131296265;
			
			// aapt resource value: 0x7f090008
			public const int cardOwnerNameInput = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int cardTypeText = 2131296262;
			
			// aapt resource value: 0x7f090001
			public const int edtEmailInput = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int edtPasswordConfirmInput = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int edtPasswordInput = 2131296258;
			
			// aapt resource value: 0x7f090018
			public const int edtPaymentAmount = 2131296280;
			
			// aapt resource value: 0x7f09000c
			public const int emailInput = 2131296268;
			
			// aapt resource value: 0x7f09001d
			public const int getReportButton = 2131296285;
			
			// aapt resource value: 0x7f09000e
			public const int loginButton = 2131296270;
			
			// aapt resource value: 0x7f09000b
			public const int loginText = 2131296267;
			
			// aapt resource value: 0x7f090021
			public const int menu_settings = 2131296289;
			
			// aapt resource value: 0x7f090010
			public const int noAccText = 2131296272;
			
			// aapt resource value: 0x7f090020
			public const int openAddCardButton = 2131296288;
			
			// aapt resource value: 0x7f09000d
			public const int passwordInput = 2131296269;
			
			// aapt resource value: 0x7f090015
			public const int pauFromBankButton = 2131296277;
			
			// aapt resource value: 0x7f09001f
			public const int payButton = 2131296287;
			
			// aapt resource value: 0x7f090017
			public const int payFromMobileButton = 2131296279;
			
			// aapt resource value: 0x7f090016
			public const int payFromVirtualButton = 2131296278;
			
			// aapt resource value: 0x7f090014
			public const int payText = 2131296276;
			
			// aapt resource value: 0x7f09000f
			public const int signupButton = 2131296271;
			
			// aapt resource value: 0x7f090004
			public const int spinUserTypes = 2131296260;
			
			// aapt resource value: 0x7f090011
			public const int textView = 2131296273;
			
			// aapt resource value: 0x7f090000
			public const int txtAccount = 2131296256;
			
			// aapt resource value: 0x7f090012
			public const int txtNotification = 2131296274;
			
			// aapt resource value: 0x7f09001a
			public const int userEmailText = 2131296282;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Account = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddCard = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Notification = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Pay = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Reader = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int UserMain = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int Options = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int Message = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int cardTypes = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int info = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int menu_settings = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int userTypes = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int dialog_animation = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
