#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("nfc_app.Resource", IsApplication=true)]

namespace nfc_app
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_menu_preferences = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080011
			public const int adFbButton = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int addFriendButton = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int askMoneyButton = 2131230740;
			
			// aapt resource value: 0x7f080004
			public const int btnCreateAccount = 2131230724;
			
			// aapt resource value: 0x7f08000d
			public const int btnDialogProceed = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int btnMakePayment = 2131230735;
			
			// aapt resource value: 0x7f080001
			public const int edtEmailInput = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int edtPasswordConfirmInput = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int edtPasswordInput = 2131230722;
			
			// aapt resource value: 0x7f08000e
			public const int edtPaymentAmount = 2131230734;
			
			// aapt resource value: 0x7f080006
			public const int emailInput = 2131230726;
			
			// aapt resource value: 0x7f080013
			public const int getReportButton = 2131230739;
			
			// aapt resource value: 0x7f080008
			public const int loginButton = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int loginText = 2131230725;
			
			// aapt resource value: 0x7f080016
			public const int menu_settings = 2131230742;
			
			// aapt resource value: 0x7f08000a
			public const int noAccText = 2131230730;
			
			// aapt resource value: 0x7f080007
			public const int passwordInput = 2131230727;
			
			// aapt resource value: 0x7f080015
			public const int payButton = 2131230741;
			
			// aapt resource value: 0x7f080009
			public const int signupButton = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int textView = 2131230731;
			
			// aapt resource value: 0x7f080000
			public const int txtAccount = 2131230720;
			
			// aapt resource value: 0x7f08000c
			public const int txtNotification = 2131230732;
			
			// aapt resource value: 0x7f080010
			public const int userEmailText = 2131230736;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Account = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Notification = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Reader = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int UserMain = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int Options = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int Message = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int info = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int menu_settings = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
