#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("nfc_app.Resource", IsApplication=true)]

namespace nfc_app
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_menu_preferences = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060013
			public const int adFbButton = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int addFriendButton = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int askMoneyButton = 2131099670;
			
			// aapt resource value: 0x7f060004
			public const int btnCreateAccount = 2131099652;
			
			// aapt resource value: 0x7f060011
			public const int btnMakePayment = 2131099665;
			
			// aapt resource value: 0x7f060001
			public const int edtEmailInput = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int edtPasswordConfirmInput = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int edtPasswordInput = 2131099650;
			
			// aapt resource value: 0x7f060010
			public const int edtPaymentAmount = 2131099664;
			
			// aapt resource value: 0x7f060006
			public const int emailInput = 2131099654;
			
			// aapt resource value: 0x7f060015
			public const int getReportButton = 2131099669;
			
			// aapt resource value: 0x7f060008
			public const int loginButton = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int loginText = 2131099653;
			
			// aapt resource value: 0x7f060018
			public const int menu_settings = 2131099672;
			
			// aapt resource value: 0x7f06000a
			public const int noAccText = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int passwordInput = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int pauFromBankButton = 2131099661;
			
			// aapt resource value: 0x7f060017
			public const int payButton = 2131099671;
			
			// aapt resource value: 0x7f06000f
			public const int payFromMobileButton = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int payFromVirtualButton = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int payText = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int signupButton = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int textView = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int txtAccount = 2131099648;
			
			// aapt resource value: 0x7f060012
			public const int userEmailText = 2131099666;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Account = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Pay = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Reader = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int UserMain = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int Options = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int info = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int menu_settings = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
